### ISSUE TITLE
Bug when a schema has a nullable AllOf ref

### ISSUE THREAD

**Issue by knivets** [p1c2u/openapi-schema-validator#20]
Hey! I have a weird issue that happens with refs that are nullable. I have the following schema:

```
"GroupWithRecentMessage": {
                "type": "object",
                "properties": {
                    "uid": {
                        "type": "string",
                        "format": "uuid",
                        "readOnly": true
                    },
                    "recent_message": {
                        "allOf": [
                            {
                                "$ref": "#/components/schemas/Message"
                            }
                        ],
                        "readOnly": true,
                        "nullable": true
                    }
                }
            }
```

Essentially what I try to express is that `recent_message` can be either `null` or an object of type `Message`.

When I run a validator it raises an exception:

```
openapi_core.unmarshalling.schemas.exceptions.InvalidSchemaValue: Value {
'results': [{'uid': '018a8f79-5098-478b-a77e-2adb685a1ea5', 'recent_message': None}]
} not valid for schema of type object: (<ValidationError: 'None for not nullable'>
```

After debugging the issue I have been able to find the root cause. I think the main reason why it happens is that [openapi-schema-validator adds](https://github.com/p1c2u/openapi-schema-validator/blob/master/openapi_schema_validator/validators.py#L70) a `"nullable": false` to each ref. So the actual schema that ends being used is the following:

```
{'nullable': False,
 'properties': {'recent_message': {'allOf': [{'$ref': '#/components/schemas/Message',
                                              'nullable': False, # <---- this is what triggers the wrong error
                                              'x-scope': ['',
                                                          '#/components/schemas/GroupWithRecentMessage']}],
                                   'nullable': True,
                                   'readOnly': True},
                'uid': {'format': 'uuid',
                        'nullable': False,
                        'readOnly': True,
                        'type': 'string'}},
 'required': ['recent_message',
              'uid'],
 'type': 'object'}
```

How can I fix this issue?

Thanks!

**Comment by claeyswo** [comment]
We are experiencing the same issue. As the previous comment stated: Perhaps @p1c2u can shed some light on why this is/was necessary?

**Comment by p1c2u** [comment]
That's exactly what comment says to trigger nullable validator.

> The comment # append defaults to trigger validator (i.e. nullable) doesn't seem to make sense as validation seems to work perfectly fine without it.

It can work fine if you define nullable param explicitly, but for schema without nullable defined (default is `False`) it won't raise validation error if you pass `None` value. You can try to remove these lines and run tests.

**Comment by ngnpope** [comment]
Maybe the issue I was bumping into was related to #24 (solved by #26), but I have been able to check.

**Comment by p1c2u** [comment]
Same here, can't reproduce the issue. @claeyswo which jsonschema version you use and do you have any example of the issue?

**Comment by claeyswo** [comment]
3.0, but by adding nullable to every item the problem was solved. By switching the nullable om some_id in the example below we get the desired effect.

``` python
schema = {
    "$ref": "#/components/schemas/TestSchema",
    "components": {
        "schemas": {
            "IntegerString": {
                "anyOf": [
                    {"type": "integer", "nullable": True},
                    {"type": "string", "nullable": True},
                ],
                "nullable": True,
            },
            "TestSchema": {
                "type": "object",
                "properties": {
                    "some_id": {
                        "$ref":  "#/components/schemas/IntegerString",
                        "nullable": True,
                    }
                },
            },
        }
    },
}
```

**Comment by p1c2u** [comment]
There were ambiguities in the semantics of `nullable` in OAS 3.0.0-2 More about the issue can be found in [the following proposal](https://github.com/OAI/OpenAPI-Specification/blob/main/proposals/2019-10-31-Clarify-Nullable.md). OAS 3.0.3 clarified the definition so it can be implemented properly. There shouldn't be any major backward compatibility issues.
