### ISSUE TITLE
jsonschema iter_errors deprecation warnings

### ISSUE THREAD

**Issue by gsgrebe** [p1c2u/openapi-schema-validator#22]
jsonschema>=4.0.0 has deprecated passing a second-argument schema to `Validator.iter_errors`

```
DeprecationWarning: Passing a schema to Validator.iter_errors is deprecated and will be removed in a future release. Call validator.evolve(schema=new_schema).iter_errors(...) instead.
```

**Comment by isi-mfurer** [comment]
this appears to be resolved (at least in my environment) in openapi-schema-validator-0.3.0

thanks!

**Comment by p1c2u** [comment]
Thanks for confirming it. Hence closing
