### ISSUE TITLE
Incompatible with jsonschema 4.10.0

### ISSUE THREAD

**Issue by Wim-De-Clercq** [p1c2u/openapi-schema-validator#46]
https://pypi.org/project/jsonschema/#history

They have created their own `evolve`  method instead of using the `attrs.evolve` and that breaks a lot.
https://github.com/python-jsonschema/jsonschema/blob/ae0feea5e5e8c1a80efb1f17a20b15295355518a/jsonschema/validators.py#L204-L216

I have also created an issue on their end: https://github.com/python-jsonschema/jsonschema/issues/982

**Comment by p1c2u** [comment]
OAS31 will be fixed but for OAS30 check the issue #48

**Comment by Wim-De-Clercq** [comment]
I believe since `4.10.2` it works again even for OAS30, due to changes on jsonschema's end (https://github.com/python-jsonschema/jsonschema/commit/a8c3b140a0134aa8c07fd7720d4e40f1bf759545).
But, as you said, it is still a technically unsupported thing.

**Comment by p1c2u** [comment]
thanks for your work on this
